---
galaxy_info:
  role_name: nginx
  namespace: x2a
  author: Benno Joy
  company: AnsibleWorks
  description: Installs and configures nginx web server
  license: BSD-3-Clause
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - web
    - nginx
    - webserver
dependencies: []
